name: Dev Build

on: 
  pull_request:
    branches:
      - dev

env:
  GODOT_VERSION: '4.3'
  GODOT_RELEASE: stable

permissions:
  contents: read
  pages: write
  packages: read
  id-token: write

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install GD Toolkit
        run: pip3 install "gdtoolkit==4.*"
      
      - name: Run GdLint
        run: gdlint ./
      
      - name: Run GdFormat
        run: gdformat ./ -s 2 -d
        continue-on-error: true
        
  export:
    name: Export for ${{ matrix.targetPlatform.name }}
    runs-on: ubuntu-latest
    needs: lint
    # runs-on: [self-hosted, "${{ matrix.targetPlatform.name }}"]
    strategy:
      fail-fast: false
      matrix:
        targetPlatform: [
          { name: win64, path: build.exe },
          { name: html5, path: index.html }
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup Godot
        uses: ./.github/actions/setup-godot
        with:
          godot-version: ${{env.GODOT_VERSION}}
          godot-release: ${{ env.GODOT_RELEASE }}
      - name: Run gd-plug
        run: |
          godot --headless -s plug.gd install
      - name: Export Godot project
        run: |
          mkdir -vp build-${{ matrix.targetPlatform.name }}
          godot --headless --export-release ${{ matrix.targetPlatform.name }} build-${{ matrix.targetPlatform.name }}/${{ matrix.targetPlatform.path }}